Repository MIEIdiscord/Rusteze, pull requests merged in 2019-10, with the labels that each got.

#23 Add info command
  src/commands.rs
Labels: command, enhancement

#25 Replace deprecated lazy_static with once_cell
  .gitignore
  Cargo.lock
  Cargo.toml
  src/channels.rs
  src/commands/admin.rs
Labels: bug

#26 Change how greeting works and adds it to config
  src/commands.rs
  src/commands/admin.rs
  src/config.rs
  src/main.rs
Labels: enhancement

#27 Add greeting message customization
  src/commands/admin.rs
  src/config.rs
  src/main.rs
Labels: bug, enhancement

#28 Add workaround to compile for arm
  Cargo.toml
Labels: bug
